apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-app-spring
  labels:
    app: meu-app-spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meu-app-spring
  template:
    metadata:
      labels:
        app: meu-app-spring
    spec:
      containers:
        - name: meu-app-spring
          image: thiagorizzo/meu-app-spring:1
          ports:
            - containerPort: 8080
