apiVersion: v1
kind: Service
metadata:
  name: meu-app-spring-service
spec:
  type: NodePort
  selector:
    app: meu-app-spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
